### ISSUE TITLE
Translate “04 Tooling & Compiler”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#22]
**File:** `manuscript/04-Tooling-and-Compiler.md`
**Branch:** `04-tooling-and-compiler`
**Original:** [`src/index.adoc#tooling-compiler`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/index.adoc#tooling-compiler)

## Sections

* [x] Getting Started with the Compiler #23
* [x] Working with the REPL #24
* [x] The Closure Library #25
* [x] Dependency management #26
* [x] External dependencies #27
* [x] Unit testing #28

**Comment by cosmonaut-ok** [comment]
I'll take it, if you don't mind =)

**Comment by roman01la** [comment]
@cosmonaut-ok Hey. Notice, that this is a chapter divided into smaller sections. You can take a section from the list above. Please read [CONTRIBUTING.md](https://github.com/LambdaBooks/clojurescript-unraveled/blob/master/CONTRIBUTING.md) before you start working on translation.

**Comment by roman01la** [comment]
@cosmonaut-ok are you still working on this chapter or any particular section?

**Comment by denysdovhan** [comment]
Done!
