### ISSUE TITLE
Translate “03 Language (the basics)”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#5]
**File:** `manuscript/03-Language-Basics.md`
**Branch:** `03-language-basics`
**Original:** [`src/index.adoc#language-the-basics`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/index.adoc#language-the-basics)

## Sections

* [x] First steps with Lisp syntax #6
* [x] The base data types #7
* [x] Vars #8
* [x] Functions #9
* [x] Flow control #10
* [x] Truthiness #11
* [x] Locals, Blocks, and Loops #12
* [x] Collection types #13
* [x] Destructuring #14
* [x] Threading Macros #15
* [x] Reader Conditionals #16
* [x] Namespaces #17
* [x] Abstractions and Polymorphism #18
* [x] Data types #19
* [x] Host interoperability #20
* [x] State management #21

**Comment by AMashoshyna** [comment]
I'd like to take this section

**Comment by roman01la** [comment]
@AMashoshyna This is actually a chapter divided into smaller sections, so it's easy to translate. You can take a section from the list above. Please read [CONTRIBUTING.md](https://github.com/LambdaBooks/clojurescript-unraveled/blob/master/CONTRIBUTING.md) before you start working on translation.

**Comment by AMashoshyna** [comment]
@roman01la oops, late night comment in a wrong thread :) Posted a comment to the right issue this time.
Thank you for link to the guidelines

**Comment by denysdovhan** [comment]
Who's working on this chapter?

**Comment by roman01la** [comment]
@denysdovhan me and @AMashoshyna at the moment
