### ISSUE TITLE
Table of content

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#50]
# Зміст

* [x] Розплутаний ClojureScript
* [x] Про цю книгу #3 (PR #38)
* [x] Вступ #4 (PR #42)
* [x] Мова (основи) #5
  - [x] Перші кроки з Lisp–синтаксисом #6 (PR #44)
  - [x] Базові типи даних #7 (PR #47)
  - [x] Вари #8 (PR #48)
  - [x] Функції #9 (PR #52)
  - [x] Керування потоком виконання #10 (PR #51)
  - [x] Істинність #11 (PR #53)
  - [x] Локальні зв'язування, блоки та цикли #12 (PR #56)
  - [x] Типи колекцій #13 (PR #58)
  - [x] Деструктурування #14 (PR #59)
  - [x] Потокові макроси #15 (PR #60)
  - [x] Умови читача #16 (PR #61)
  - [x] Простори імен #17 (PR #62)
  - [x] Абстракції і поліморфізм #18 (PR #63)
  - [x] Типи даних #19 (PR #64)
  - [x] Сумісність з батьківською платформою #20 (PR #68)
  - [x] Керування станом #21 (PR #71)
* [x] Інструментарій та компілятор #22 
  - [x] Починаємо працювати з компілятором #23 (PR #70)
  - [x] Робота з REPL #24 (PR #65)
  - [x] Бібліотека Closure #25 (PR #72)
  - [x] Керування залежностями #26 (PR #75)
  - [x] Зовнішні залежності #27 (PR #76)
  - [x] Модульне тестування #28 (PR #74)
* [x] Мова (поглиблені теми) #29 
  - [x] Перетворювачі #30 (PR #78)
  - [x] Перехідні структури даних #31 (PR #66)
  - [x] Метадані #32 (PR #77)
  - [x] Основні протоколи #33 
  - [x] CSP (з core.async) #34
* [x] Додатки #35 
  - Додаток А: Інтерактивна розробка з Figwheel
  - Додаток Б: Встановлення середовища розробки на ClojureScript
* [x] Подяки #36 
* [x] Подальше читання #37

**Comment by denysdovhan** [comment]
Done! The book is translated!

**Comment by roman01la** [comment]
Wow! Great work everyone! 🎉
